-- SUGGESTED TEMPLATING (REVIEW CAREFULLY):
-- This file contains suggested changes for multi-environment deployment
-- ⚠️  MANUAL REVIEW REQUIRED before using
-- Applied 0 safe suggestions

-- Grants exported from PLATFORM_SIT at 20250829161026
-- Environment references templated for multi-environment deployment
GRANT OWNERSHIP ON SCHEMA IDENTIFIER('{{ DB_PREFIX }}_{{ DB_BASE }}_{{ ENV }}.CONFIG') TO ROLE DATAADMIN WITH GRANT OPTION;
GRANT CREATE TABLE ON SCHEMA IDENTIFIER('{{ DB_PREFIX }}_{{ DB_BASE }}_{{ ENV }}.CONFIG') TO DATABASE_ROLE FULL_ACCESS;
GRANT CREATE VIEW ON SCHEMA IDENTIFIER('{{ DB_PREFIX }}_{{ DB_BASE }}_{{ ENV }}.CONFIG') TO DATABASE_ROLE FULL_ACCESS;
GRANT USAGE ON SCHEMA IDENTIFIER('{{ DB_PREFIX }}_{{ DB_BASE }}_{{ ENV }}.CONFIG') TO DATABASE_ROLE FULL_ACCESS WITH GRANT OPTION;
GRANT USAGE ON SCHEMA IDENTIFIER('{{ DB_PREFIX }}_{{ DB_BASE }}_{{ ENV }}.CONFIG') TO ROLE PROD_PREPARE_ROLE;
GRANT USAGE ON SCHEMA IDENTIFIER('{{ DB_PREFIX }}_{{ DB_BASE }}_{{ ENV }}.CONFIG') TO DATABASE_ROLE READ_ONLY;
GRANT USAGE ON SCHEMA IDENTIFIER('{{ DB_PREFIX }}_{{ DB_BASE }}_{{ ENV }}.CONFIG') TO ROLE ROLE_APP_CONSUME_SIT;
GRANT USAGE ON SCHEMA IDENTIFIER('{{ DB_PREFIX }}_{{ DB_BASE }}_{{ ENV }}.CONFIG') TO ROLE ROLE_APP_DMC_CONFIG_SIT;
GRANT USAGE ON SCHEMA IDENTIFIER('{{ DB_PREFIX }}_{{ DB_BASE }}_{{ ENV }}.CONFIG') TO ROLE ROLE_APP_OPSAUTOMATION_SIT;
GRANT CREATE TABLE ON SCHEMA IDENTIFIER('{{ DB_PREFIX }}_{{ DB_BASE }}_{{ ENV }}.CONFIG') TO ROLE ROLE_APP_SETUP_SIT;
GRANT CREATE VIEW ON SCHEMA IDENTIFIER('{{ DB_PREFIX }}_{{ DB_BASE }}_{{ ENV }}.CONFIG') TO ROLE ROLE_APP_SETUP_SIT;
GRANT USAGE ON SCHEMA IDENTIFIER('{{ DB_PREFIX }}_{{ DB_BASE }}_{{ ENV }}.CONFIG') TO ROLE ROLE_APP_SETUP_SIT;
GRANT USAGE ON SCHEMA IDENTIFIER('{{ DB_PREFIX }}_{{ DB_BASE }}_{{ ENV }}.CONFIG') TO ROLE ROLE_MAP_SIT;
GRANT USAGE ON SCHEMA IDENTIFIER('{{ DB_PREFIX }}_{{ DB_BASE }}_{{ ENV }}.CONFIG') TO ROLE ROLE_PIPELINE_SIT;
GRANT USAGE ON SCHEMA IDENTIFIER('{{ DB_PREFIX }}_{{ DB_BASE }}_{{ ENV }}.CONFIG') TO ROLE ROLE_TEAM_OPSAUTOMATION_SIT;
GRANT ADD SEARCH OPTIMIZATION ON SCHEMA IDENTIFIER('{{ DB_PREFIX }}_{{ DB_BASE }}_{{ ENV }}.CONFIG') TO ROLE SIT_PREPARE_ROLE;
GRANT APPLYBUDGET ON SCHEMA IDENTIFIER('{{ DB_PREFIX }}_{{ DB_BASE }}_{{ ENV }}.CONFIG') TO ROLE SIT_PREPARE_ROLE;
GRANT CREATE AGGREGATION POLICY ON SCHEMA IDENTIFIER('{{ DB_PREFIX }}_{{ DB_BASE }}_{{ ENV }}.CONFIG') TO ROLE SIT_PREPARE_ROLE;
GRANT CREATE ALERT ON SCHEMA IDENTIFIER('{{ DB_PREFIX }}_{{ DB_BASE }}_{{ ENV }}.CONFIG') TO ROLE SIT_PREPARE_ROLE;
GRANT CREATE AUTHENTICATION POLICY ON SCHEMA IDENTIFIER('{{ DB_PREFIX }}_{{ DB_BASE }}_{{ ENV }}.CONFIG') TO ROLE SIT_PREPARE_ROLE;
GRANT CREATE CORTEX SEARCH SERVICE ON SCHEMA IDENTIFIER('{{ DB_PREFIX }}_{{ DB_BASE }}_{{ ENV }}.CONFIG') TO ROLE SIT_PREPARE_ROLE;
GRANT CREATE DATA METRIC FUNCTION ON SCHEMA IDENTIFIER('{{ DB_PREFIX }}_{{ DB_BASE }}_{{ ENV }}.CONFIG') TO ROLE SIT_PREPARE_ROLE;
GRANT CREATE DATASET ON SCHEMA IDENTIFIER('{{ DB_PREFIX }}_{{ DB_BASE }}_{{ ENV }}.CONFIG') TO ROLE SIT_PREPARE_ROLE;
GRANT CREATE DYNAMIC TABLE ON SCHEMA IDENTIFIER('{{ DB_PREFIX }}_{{ DB_BASE }}_{{ ENV }}.CONFIG') TO ROLE SIT_PREPARE_ROLE;
GRANT CREATE EVENT TABLE ON SCHEMA IDENTIFIER('{{ DB_PREFIX }}_{{ DB_BASE }}_{{ ENV }}.CONFIG') TO ROLE SIT_PREPARE_ROLE;
GRANT CREATE EXTERNAL TABLE ON SCHEMA IDENTIFIER('{{ DB_PREFIX }}_{{ DB_BASE }}_{{ ENV }}.CONFIG') TO ROLE SIT_PREPARE_ROLE;
GRANT CREATE FILE FORMAT ON SCHEMA IDENTIFIER('{{ DB_PREFIX }}_{{ DB_BASE }}_{{ ENV }}.CONFIG') TO ROLE SIT_PREPARE_ROLE;
GRANT CREATE FUNCTION ON SCHEMA IDENTIFIER('{{ DB_PREFIX }}_{{ DB_BASE }}_{{ ENV }}.CONFIG') TO ROLE SIT_PREPARE_ROLE;
GRANT CREATE GIT REPOSITORY ON SCHEMA IDENTIFIER('{{ DB_PREFIX }}_{{ DB_BASE }}_{{ ENV }}.CONFIG') TO ROLE SIT_PREPARE_ROLE;
GRANT CREATE ICEBERG TABLE ON SCHEMA IDENTIFIER('{{ DB_PREFIX }}_{{ DB_BASE }}_{{ ENV }}.CONFIG') TO ROLE SIT_PREPARE_ROLE;
GRANT CREATE IMAGE REPOSITORY ON SCHEMA IDENTIFIER('{{ DB_PREFIX }}_{{ DB_BASE }}_{{ ENV }}.CONFIG') TO ROLE SIT_PREPARE_ROLE;
GRANT CREATE MASKING POLICY ON SCHEMA IDENTIFIER('{{ DB_PREFIX }}_{{ DB_BASE }}_{{ ENV }}.CONFIG') TO ROLE SIT_PREPARE_ROLE;
GRANT CREATE MATERIALIZED VIEW ON SCHEMA IDENTIFIER('{{ DB_PREFIX }}_{{ DB_BASE }}_{{ ENV }}.CONFIG') TO ROLE SIT_PREPARE_ROLE;
GRANT CREATE MODEL ON SCHEMA IDENTIFIER('{{ DB_PREFIX }}_{{ DB_BASE }}_{{ ENV }}.CONFIG') TO ROLE SIT_PREPARE_ROLE;
GRANT CREATE NETWORK RULE ON SCHEMA IDENTIFIER('{{ DB_PREFIX }}_{{ DB_BASE }}_{{ ENV }}.CONFIG') TO ROLE SIT_PREPARE_ROLE;
GRANT CREATE NOTEBOOK ON SCHEMA IDENTIFIER('{{ DB_PREFIX }}_{{ DB_BASE }}_{{ ENV }}.CONFIG') TO ROLE SIT_PREPARE_ROLE;
GRANT CREATE PACKAGES POLICY ON SCHEMA IDENTIFIER('{{ DB_PREFIX }}_{{ DB_BASE }}_{{ ENV }}.CONFIG') TO ROLE SIT_PREPARE_ROLE;
GRANT CREATE PASSWORD POLICY ON SCHEMA IDENTIFIER('{{ DB_PREFIX }}_{{ DB_BASE }}_{{ ENV }}.CONFIG') TO ROLE SIT_PREPARE_ROLE;
GRANT CREATE PIPE ON SCHEMA IDENTIFIER('{{ DB_PREFIX }}_{{ DB_BASE }}_{{ ENV }}.CONFIG') TO ROLE SIT_PREPARE_ROLE;
GRANT CREATE PRIVACY POLICY ON SCHEMA IDENTIFIER('{{ DB_PREFIX }}_{{ DB_BASE }}_{{ ENV }}.CONFIG') TO ROLE SIT_PREPARE_ROLE;
GRANT CREATE PROCEDURE ON SCHEMA IDENTIFIER('{{ DB_PREFIX }}_{{ DB_BASE }}_{{ ENV }}.CONFIG') TO ROLE SIT_PREPARE_ROLE;
GRANT CREATE PROJECTION POLICY ON SCHEMA IDENTIFIER('{{ DB_PREFIX }}_{{ DB_BASE }}_{{ ENV }}.CONFIG') TO ROLE SIT_PREPARE_ROLE;
GRANT CREATE RESOURCE GROUP ON SCHEMA IDENTIFIER('{{ DB_PREFIX }}_{{ DB_BASE }}_{{ ENV }}.CONFIG') TO ROLE SIT_PREPARE_ROLE;
GRANT CREATE ROW ACCESS POLICY ON SCHEMA IDENTIFIER('{{ DB_PREFIX }}_{{ DB_BASE }}_{{ ENV }}.CONFIG') TO ROLE SIT_PREPARE_ROLE;
GRANT CREATE SECRET ON SCHEMA IDENTIFIER('{{ DB_PREFIX }}_{{ DB_BASE }}_{{ ENV }}.CONFIG') TO ROLE SIT_PREPARE_ROLE;
GRANT CREATE SEQUENCE ON SCHEMA IDENTIFIER('{{ DB_PREFIX }}_{{ DB_BASE }}_{{ ENV }}.CONFIG') TO ROLE SIT_PREPARE_ROLE;
GRANT CREATE SERVICE ON SCHEMA IDENTIFIER('{{ DB_PREFIX }}_{{ DB_BASE }}_{{ ENV }}.CONFIG') TO ROLE SIT_PREPARE_ROLE;
GRANT CREATE SERVICE CLASS ON SCHEMA IDENTIFIER('{{ DB_PREFIX }}_{{ DB_BASE }}_{{ ENV }}.CONFIG') TO ROLE SIT_PREPARE_ROLE;
GRANT CREATE SESSION POLICY ON SCHEMA IDENTIFIER('{{ DB_PREFIX }}_{{ DB_BASE }}_{{ ENV }}.CONFIG') TO ROLE SIT_PREPARE_ROLE;
GRANT CREATE SNAPSHOT ON SCHEMA IDENTIFIER('{{ DB_PREFIX }}_{{ DB_BASE }}_{{ ENV }}.CONFIG') TO ROLE SIT_PREPARE_ROLE;
GRANT CREATE STAGE ON SCHEMA IDENTIFIER('{{ DB_PREFIX }}_{{ DB_BASE }}_{{ ENV }}.CONFIG') TO ROLE SIT_PREPARE_ROLE;
GRANT CREATE STREAM ON SCHEMA IDENTIFIER('{{ DB_PREFIX }}_{{ DB_BASE }}_{{ ENV }}.CONFIG') TO ROLE SIT_PREPARE_ROLE;
GRANT CREATE STREAMLIT ON SCHEMA IDENTIFIER('{{ DB_PREFIX }}_{{ DB_BASE }}_{{ ENV }}.CONFIG') TO ROLE SIT_PREPARE_ROLE;
GRANT CREATE TABLE ON SCHEMA IDENTIFIER('{{ DB_PREFIX }}_{{ DB_BASE }}_{{ ENV }}.CONFIG') TO ROLE SIT_PREPARE_ROLE;
GRANT CREATE TAG ON SCHEMA IDENTIFIER('{{ DB_PREFIX }}_{{ DB_BASE }}_{{ ENV }}.CONFIG') TO ROLE SIT_PREPARE_ROLE;
GRANT CREATE TASK ON SCHEMA IDENTIFIER('{{ DB_PREFIX }}_{{ DB_BASE }}_{{ ENV }}.CONFIG') TO ROLE SIT_PREPARE_ROLE;
GRANT CREATE TEMPORARY TABLE ON SCHEMA IDENTIFIER('{{ DB_PREFIX }}_{{ DB_BASE }}_{{ ENV }}.CONFIG') TO ROLE SIT_PREPARE_ROLE;
GRANT CREATE VIEW ON SCHEMA IDENTIFIER('{{ DB_PREFIX }}_{{ DB_BASE }}_{{ ENV }}.CONFIG') TO ROLE SIT_PREPARE_ROLE;
GRANT MODIFY ON SCHEMA IDENTIFIER('{{ DB_PREFIX }}_{{ DB_BASE }}_{{ ENV }}.CONFIG') TO ROLE SIT_PREPARE_ROLE;
GRANT MONITOR ON SCHEMA IDENTIFIER('{{ DB_PREFIX }}_{{ DB_BASE }}_{{ ENV }}.CONFIG') TO ROLE SIT_PREPARE_ROLE;
GRANT USAGE ON SCHEMA IDENTIFIER('{{ DB_PREFIX }}_{{ DB_BASE }}_{{ ENV }}.CONFIG') TO ROLE SIT_PREPARE_ROLE;
GRANT USAGE ON SCHEMA IDENTIFIER('{{ DB_PREFIX }}_{{ DB_BASE }}_{{ ENV }}.CONFIG') TO SHARE SJB11964.SHARE_MANAGED_GLOBAL_ALL_PLATFORM_SIT;