-- FINAL VERSION: DATA_AMS Schema
-- Generated at: 2025-08-29T14:58:14.591352
-- Note: No templating decisions were made - using raw extraction
-- ⚠️  This version may contain environment-specific references

-- Exported from ALTO_SIT at 20250829145710
-- Environment references templated for multi-environment deployment
-- NOTE: Only current database references are templated, cross-database references remain as-is
create or replace TABLE AMS_META_PERMISSIONS (
	PUBLICID VARCHAR(256),
	ID VARCHAR(256),
	APPLIEDON VARCHAR(256),
	OPERATIONCODE VARCHAR(256),
	RESOURCETYPE VARCHAR(256),
	NAMESPACE VARCHAR(256),
	INSTANCEID VARCHAR(256)
);
create or replace TABLE AMS_META_USERS (
	ID VARCHAR(256),
	DISPLAY_NAME VARCHAR(256),
	ORGANISATIONNAME VARCHAR(256),
	ROLENAME VARCHAR(256),
	ACCOUNTNAME VARCHAR(256)
);
create or replace TABLE STAGING_AMS_META_PERMISSIONS (
	PUBLICID VARCHAR(256),
	ID VARCHAR(256),
	APPLIEDON VARCHAR(256),
	OPERATIONCODE VARCHAR(256),
	RESOURCETYPE VARCHAR(256),
	NAMESPACE VARCHAR(256),
	INSTANCEID VARCHAR(256)
);
create or replace TABLE STAGING_AMS_META_USERS (
	ID VARCHAR(256),
	DISPLAY_NAME VARCHAR(256),
	ORGANISATIONNAME VARCHAR(256),
	ROLENAME VARCHAR(256),
	ACCOUNTNAME VARCHAR(256)
);
create or replace TABLE TEMP_AMS_PERMISSIONS (
	PUBLICID VARCHAR(256),
	ID VARCHAR(256),
	APPLIEDON VARCHAR(256),
	OPERATIONCODE VARCHAR(256),
	RESOURCETYPE VARCHAR(256),
	NAMESPACE VARCHAR(256),
	INSTANCEID VARCHAR(256)
);