# connections.toml — for schemachange v4

# =============================================================================
# ALTO DATABASE CONNECTIONS
# =============================================================================

# Source connections for ALTO database schemas
[SRC_DATA_AMS]
account = "KINESSO-KINESSO"
user = "PAVAN.KUMAR@KINESSO.COM"
authenticator = "externalbrowser"
role = "ACCOUNTADMIN"
warehouse = "GR_DATA_TEAM_PROD"
database = "ALTO_{{ENV}}"
schema = "DATA_AMS"

# Target connections for ALTO database schemas
[TGT_DATA_AMS]
account = "KINESSO-KINESSO"
user = "PAVAN.KUMAR@KINESSO.COM"
authenticator = "externalbrowser"
role = "ACCOUNTADMIN"
warehouse = "GR_DATA_TEAM_PROD"
database = "{{DB_PREFIX}}_ALTO_{{ENV}}"
schema = "DATA_AMS"

# =============================================================================
# PLATFORM DATABASE CONNECTIONS
# =============================================================================

# Source connections for PLATFORM database schemas
[SRC_REPORTINGAPPS]
account = "KINESSO-KINESSO_REPORTING"
user = "PAVAN.KUMAR@KINESSO.COM"
authenticator = "externalbrowser"
role = "DATAADMIN"
warehouse = "WH_APP_UPLOAD_XS_{{ENV}}"
database = "PLATFORM_{{ENV}}"
schema = "REPORTINGAPPS"

# Target connections for PLATFORM database schemas
[TGT_REPORTINGAPPS]
account = "KINESSO-KINESSO"
user = "PAVAN.KUMAR@KINESSO.COM"
authenticator = "externalbrowser"
role = "DATAADMIN"
warehouse = "WH_APP_UPLOAD_XS_{{ENV}}"
database = "{{DB_PREFIX}}_PLATFORM_{{ENV}}"
schema = "REPORTINGAPPS"

# =============================================================================

# Source connections for PLATFORM database schemas
[SRC_CONFIG]
account = "KINESSO-KINESSO_REPORTING"
user = "PAVAN.KUMAR@KINESSO.COM"
authenticator = "externalbrowser"
role = "DATAADMIN"
warehouse = "WH_APP_UPLOAD_XS_{{ENV}}"
database = "PLATFORM_{{ENV}}"
schema = "CONFIG"

# Target connections for PLATFORM database schemas
[TGT_CONFIG]
account = "KINESSO-KINESSO"
user = "PAVAN.KUMAR@KINESSO.COM"
authenticator = "externalbrowser"
role = "DATAADMIN"
warehouse = "WH_APP_UPLOAD_XS_{{ENV}}"
database = "{{DB_PREFIX}}_PLATFORM_{{ENV}}"
schema = "CONFIG"